### ISSUE TITLE
Slow `Updating crates.io index`

### ISSUE THREAD

**Issue by TastyFrenchBun** [TastyFrenchBun/mena-rust#3]
Tried to use this, but both didn't help ;(
```toml
[net]
git-fetch-with-cli = true

[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"
```
